### ISSUE TITLE
Add Sunbird Partners Section to Participate page

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/project-sunbird.github.io#129]
Need to add a section on Sunbird Partners to the sunbird.org Participate page. 

Section will contain logos and links to the projects which support Sunbird.

**Comment by Sunitashelar** [comment]
@joel@ekstep.org request you to provide details and logo for PhraseApp

**Comment by Sunitashelar** [comment]
Hi Joel,

As discussed with Shailesh, need the PhraseApp logo, to add as a participating partner.

Hi Deepika, Vikram,

Hope this is fine.

Regards,
Sunita

Sent from Mail for Windows 10

**Comment by joel-ekstep** [comment]
@Sunitashelar Some feedback regarding the participate page - "...leave your mark to impact a million minds".

Can we change million to billion?

**Comment by Sunitashelar** [comment]
Sure Joel. Will make both changes together.

**Comment by nawabahmadreshi** [comment]
done and published here http://www.sunbird.org/partner/

**Comment by kochhar** [comment]
@nawabahmadreshi the development partner logo link back to the sunbird.org page. Is this intentional?

**Comment by Sunitashelar** [comment]
@kochhar, right now this is intentional. We need clarity from Deepika from legal and Madhu to give back links to all development partners. Am in touch with them. Will get it sorted within a few days and make the changes, if required. The back link to the solution partner was an urgent requirement so that we would get the solution free of cost to work with Sunbird and EkStep infra.
