### ISSUE TITLE
Some changes are required in create user api.

### ISSUE THREAD

**Issue by manzarul** [project-sunbird/project-sunbird.github.io#257]
Link of the page: http://www.sunbird.org/apis/userapi/#operation/Create%20User
Changes Required: 
                               header  "X-Authenticated-Userid" is not required in this api request.
                                2. firstName,password,email,userName,phone are required fields only .
                              other's are optional fields.
                           Please remove "aadhaarNo" filed from request body. 
                           And "dob" field format should be "YYYY-MM-dd" example: "2016-04-30" 

@nawabahmadreshi

**Comment by kochhar** [comment]
cc: @Sunitashelar this issue has not been addressed for 13 days.

**Comment by nawabahmadreshi** [comment]
@kochhar this task was taken up by @manzarul and it is done. Yes, few other APIs need changes in parameters ( setting required to optional) but due to other tasks in the planned pipeline, will take it up as per doc team planning
FYI :
It was discussed with Manzarul that, he can do the necessary changes and send a pull request which I will review and merged. 
https://github.com/project-sunbird/project-sunbird.github.io/pull/258/files
CC: 
@Sunitashelar

**Comment by kochhar** [comment]
Bugs must be prioritise before new docs. Please follow this prioritisation
policy.
